/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: chord.io
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package io.chord.client.models

import com.squareup.moshi.Json
import org.threeten.bp.ZonedDateTime

/**
 * 
 * @property accessToken 
 * @property refreshToken 
 * @property expiresIn 
 * @property refreshExpiresIn 
 * @property expirationDate 
 * @property refreshExpirationDate 
 */
data class Authentication (
        @Json(name = "access_token") @field:Json(name = "access_token") var accessToken: String? = null,
        @Json(name = "refresh_token") @field:Json(name = "refresh_token") var refreshToken: String? = null,
        @Json(name = "expires_in") @field:Json(name = "expires_in") var expiresIn: Int? = null,
        @Json(name = "refresh_expires_in") @field:Json(name = "refresh_expires_in") var refreshExpiresIn: Int? = null,
        @Json(name = "expiration_date") @field:Json(name = "expiration_date") var expirationDate: ZonedDateTime? = null,
        @Json(name = "refresh_expiration_date") @field:Json(name = "refresh_expiration_date") var refreshExpirationDate: ZonedDateTime? = null
)

