/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: chord.io
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package io.chord.client.models

import com.squareup.moshi.Json

/**
 * 
 * @property position 
 * @property length 
 * @property pitch 
 */
data class FingeringEntry (
        @Json(name = "position") @field:Json(name = "position") var position: Double,
        @Json(name = "length") @field:Json(name = "length") var length: Double,
        @Json(name = "pitch") @field:Json(name = "pitch") var pitch: Int
)

