/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: chord.io
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package io.chord.client.models

import com.squareup.moshi.Json

/**
* 
* Values: DIMINISHED,MINOR,PERFECT,MAJOR,AUGMENTED
*/
enum class IntervalQuality(val value: String){
    @Json(name = "Diminished") DIMINISHED("Diminished"),
    @Json(name = "Minor") MINOR("Minor"),
    @Json(name = "Perfect") PERFECT("Perfect"),
    @Json(name = "Major") MAJOR("Major"),
    @Json(name = "Augmented") AUGMENTED("Augmented")
}

