/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: chord.io
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package io.chord.client.models

import com.squareup.moshi.Json

/**
* 
* Values: SHORT,MEDIUM,FORMULA
*/
enum class IntervalFormat(val value: String){
    @Json(name = "Short") SHORT("Short"),
    @Json(name = "Medium") MEDIUM("Medium"),
    @Json(name = "Formula") FORMULA("Formula")
}

