/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: chord.io
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package io.chord.client.models

import com.squareup.moshi.Json

/**
 * 
 * @property a 
 * @property b 
 */
data class NotePairDto (
        @Json(name = "a") @field:Json(name = "a") var a: NoteDto,
        @Json(name = "b") @field:Json(name = "b") var b: NoteDto
)

