/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: chord.io
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package io.chord.client.models

import com.squareup.moshi.Json

/**
 * 
 * @property key 
 * @property picth 
 * @property alteration 
 */
data class NoteDto (
        @Json(name = "key") @field:Json(name = "key") var key: String,
        @Json(name = "picth") @field:Json(name = "picth") var picth: Int,
        @Json(name = "alteration") @field:Json(name = "alteration") var alteration: Int
)

