/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: chord.io
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package io.chord.client.models

import com.squareup.moshi.Json

/**
 * 
 * @property name 
 * @property authorId 
 * @property tempo 
 * @property isPrivate 
 * @property tracks 
 * @property themes 
 */
data class ProjectDto (
        @Json(name = "name") @field:Json(name = "name") var name: String,
        @Json(name = "author_id") @field:Json(name = "author_id") var authorId: String,
        @Json(name = "tempo") @field:Json(name = "tempo") var tempo: Int,
        @Json(name = "is_private") @field:Json(name = "is_private") var isPrivate: Boolean,
        @Json(name = "tracks") @field:Json(name = "tracks") var tracks: List<Track>,
        @Json(name = "themes") @field:Json(name = "themes") var themes: List<Theme>
)

