/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: chord.io
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package io.chord.client.models

import com.squareup.moshi.Json

/**
 * 
 * @property id 
 * @property name 
 * @property tempo 
 * @property isPrivate 
 * @property tracks 
 */
data class Project (
        @Json(name = "id") @field:Json(name = "id") var id: String,
        @Json(name = "name") @field:Json(name = "name") var name: String,
        @Json(name = "tempo") @field:Json(name = "tempo") var tempo: Int,
        @Json(name = "is_private") @field:Json(name = "is_private") var isPrivate: Boolean,
        @Json(name = "tracks") @field:Json(name = "tracks") var tracks: List<Track>
)

