/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: chord.io
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package io.chord.client.apis

import okhttp3.RequestBody

import io.chord.client.models.Authentication
import io.chord.client.models.SignInDto
import io.chord.client.models.User
import io.chord.client.models.UserDto
import io.chord.client.models.ValidationProblemDetails
import io.reactivex.Completable
import io.reactivex.Single
import retrofit2.http.GET
import retrofit2.http.Headers
import retrofit2.http.POST

@JvmSuppressWildcards
interface AuthenticationApi {
  /**
   * The endpoint is owned by chord.io.api service owner
   * @param refreshToken  (optional)
   */
  @Headers(
    "X-Operation-Id: Refresh"
  )
  @GET("/api/authentication/refresh")
  fun refresh(
    @retrofit2.http.Header("refresh_token") refreshToken: String?
  ): Single<Authentication>

  /**
   * The endpoint is owned by chord.io.api service owner
   * @param body  (optional)
   */
  @Headers(
    "X-Operation-Id: SignIn",
    "Content-Type: application/json-patch+json"
  )
  @POST("/api/authentication/sign-in")
  fun signIn(
    @retrofit2.http.Body  body: SignInDto
  ): Single<Authentication>

  /**
   * The endpoint is owned by chord.io.api service owner
   * @param refreshToken  (optional)
   */
  @Headers(
    "X-Operation-Id: SignOut"
  )
  @GET("/api/authentication/sign-out")
  fun signOut(
    @retrofit2.http.Header("refresh_token") refreshToken: String?
  ): Completable

  /**
   * The endpoint is owned by chord.io.api service owner
   * @param body  (optional)
   */
  @Headers(
    "X-Operation-Id: SignUp",
    "Content-Type: application/json-patch+json"
  )
  @POST("/api/authentication/sign-up")
  fun signUp(
    @retrofit2.http.Body  body: UserDto
  ): Single<User>

}
