/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: chord.io
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package io.chord.client.apis

import okhttp3.RequestBody

import io.chord.client.models.User
import io.chord.client.models.UserDto
import io.chord.client.models.ValidationProblemDetails
import io.reactivex.Completable
import io.reactivex.Single
import retrofit2.http.DELETE
import retrofit2.http.Headers
import retrofit2.http.POST
import retrofit2.http.PUT

@JvmSuppressWildcards
interface UsersApi {
  /**
   * The endpoint is owned by chord.io.api service owner
   * @param body  (optional)
   */
  @Headers(
    "X-Operation-Id: Create",
    "Content-Type: application/json-patch+json"
  )
  @POST("/api/users")
  fun create(
    @retrofit2.http.Body  body: UserDto
  ): Single<User>

  /**
   * The endpoint is owned by chord.io.api service owner
   * @param id  (required)
   */
  @Headers(
    "X-Operation-Id: Delete"
  )
  @DELETE("/api/users/{id}")
  fun delete(
    @retrofit2.http.Path("id") id: String
  ): Completable

  /**
   * The endpoint is owned by chord.io.api service owner
   * @param id  (required)
   * @param body  (optional)
   */
  @Headers(
    "X-Operation-Id: Update",
    "Content-Type: application/json-patch+json"
  )
  @PUT("/api/users/{id}")
  fun update(
    @retrofit2.http.Path("id") id: String,
    @retrofit2.http.Body  body: UserDto
  ): Completable

}
