/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: chord.io
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package io.chord.clients.models

import com.squareup.moshi.Json

/**
 * 
 * @property root 
 * @property intervals 
 * @property length 
 * @property fingering 
 */
data class Chord (
        @Json(name = "root") @field:Json(name = "root") var root: Int,
        @Json(name = "intervals") @field:Json(name = "intervals") var intervals: List<String>,
        @Json(name = "length") @field:Json(name = "length") var length: ChordLength,
        @Json(name = "fingering") @field:Json(name = "fingering") var fingering: List<FingeringEntry>
)

