/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: chord.io
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package io.chord.clients.models

import com.squareup.moshi.Json

/**
 * 
 * @property errors 
 * @property type 
 * @property title 
 * @property status 
 * @property detail 
 * @property instance 
 * @property extensions 
 */
data class ValidationProblemDetails (
        @Json(name = "errors") @field:Json(name = "errors") var errors: Map<String, List<String>>? = null,
        @Json(name = "type") @field:Json(name = "type") var type: String? = null,
        @Json(name = "title") @field:Json(name = "title") var title: String? = null,
        @Json(name = "status") @field:Json(name = "status") var status: Int? = null,
        @Json(name = "detail") @field:Json(name = "detail") var detail: String? = null,
        @Json(name = "instance") @field:Json(name = "instance") var instance: String? = null,
        @Json(name = "extensions") @field:Json(name = "extensions") var extensions: Map<String, Object>? = null
)

